## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("..\Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
0,0,Dakar,SN,2021-11-04,14.6937,-17.4441,88.68,79,0,6.91,clear sky
1,1,Husavik,IS,2021-11-04,66.0449,-17.3389,40.91,99,66,8.43,broken clouds
2,2,Rikitea,PF,2021-11-04,-23.1203,-134.9692,73.58,78,100,12.59,light rain
3,3,Lavrentiya,RU,2021-11-04,65.5833,-171.0000,14.27,82,100,12.03,overcast clouds
4,4,Thinadhoo,MV,2021-11-04,0.5333,72.9333,83.50,67,100,13.15,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 55
What is the maximum temperature you would like for your trip? 80

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_initial_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                   (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_initial_df.head(20)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Description
2,2,Rikitea,PF,2021-11-04,-23.1203,-134.9692,73.58,78,100,12.59,light rain
5,5,Bredasdorp,ZA,2021-11-04,-34.5322,20.0403,65.52,63,100,25.32,overcast clouds
6,6,Geraldton,AU,2021-11-04,-28.7667,114.6000,63.01,77,90,12.66,overcast clouds
9,9,Faya,SA,2021-11-04,18.3851,42.4509,64.51,35,0,3.24,clear sky
10,10,Vaini,TO,2021-11-04,-21.2000,-175.2000,75.36,100,75,5.75,light rain
11,11,Venice,US,2021-11-04,27.0998,-82.4543,77.99,81,1,5.01,clear sky
12,12,Alofi,NU,2021-11-04,-19.0595,-169.9187,75.09,88,100,3.44,overcast clouds
13,13,Kattivakkam,IN,2021-11-04,13.2167,80.3167,78.89,85,98,5.64,overcast clouds
15,15,Faanui,PF,2021-11-04,-16.4833,-151.7500,78.82,75,24,10.80,few clouds
17,17,Carnarvon,AU,2021-11-04,-24.8667,113.6333,66.27,68,90,19.57,overcast clouds
21,21,Buala,SB,2021-11-04,-8.1450,159.5921,79.56,80,100,5.50,overcast clouds
22,22,Avarua,CK,2021-11-04,-21.2078,-159.7750,75.25,73,29,4.61,light rain
23,23,Port Elizabeth,ZA,2021-11-04,-33.9180,25.5701,64.69,68,0,4.61,clear sky
24,24,Kapaa,US,2021-11-04,22.0752,-159.3190,75.52,83,90,3.00,heavy intensity rain
33,33,Saint George,US,2021-11-04,37.1041,-113.5841,75.67,46,1,1.01,clear sky
34,34,Ushuaia,AR,2021-11-04,-54.8000,-68.3000,55.06,44,75,8.05,broken clouds
41,41,Saldanha,ZA,2021-11-04,-33.0117,17.9442,66.25,85,95,9.89,overcast clouds
42,42,Port Lincoln,AU,2021-11-04,-34.7333,135.8667,57.24,86,58,11.72,broken clouds
45,45,San Julian,MX,2021-11-04,21.0167,-102.1667,74.19,33,24,4.36,few clouds
46,46,Hilo,US,2021-11-04,19.7297,-155.0900,79.29,76,20,5.75,few clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_initial_df.count()

City_ID        280
City           280
Country        279
Date           280
Lat            280
Lng            280
Max Temp       280
Humidity       280
Cloudiness     280
Wind Speed     280
Description    280
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
pref_cities_df = preferred_cities_initial_df.dropna()
pref_cities_df.count()

City_ID        279
City           279
Country        279
Date           279
Lat            279
Lng            279
Max Temp       279
Humidity       279
Cloudiness     279
Wind Speed     279
Description    279
dtype: int64

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = pref_cities_df[["City", "Country", "Max Temp", "Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
2,Rikitea,PF,73.58,light rain,-23.1203,-134.9692,
5,Bredasdorp,ZA,65.52,overcast clouds,-34.5322,20.0403,
6,Geraldton,AU,63.01,overcast clouds,-28.7667,114.6000,
9,Faya,SA,64.51,clear sky,18.3851,42.4509,
10,Vaini,TO,75.36,light rain,-21.2000,-175.2000,
11,Venice,US,77.99,clear sky,27.0998,-82.4543,
12,Alofi,NU,75.09,overcast clouds,-19.0595,-169.9187,
13,Kattivakkam,IN,78.89,overcast clouds,13.2167,80.3167,
15,Faanui,PF,78.82,few clouds,-16.4833,-151.7500,
17,Carnarvon,AU,66.27,overcast clouds,-24.8667,113.6333,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        
print("-----------------------------")
print("Data Retrieval Complete      ")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
-----------------------------
Data Retrieval Complete

In [9]:
hotel_df.head(20)

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
2,Rikitea,PF,73.58,light rain,-23.1203,-134.9692,People ThankYou
5,Bredasdorp,ZA,65.52,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
6,Geraldton,AU,63.01,overcast clouds,-28.7667,114.6000,Broadwater Mariner Resort
9,Faya,SA,64.51,clear sky,18.3851,42.4509,املاك خالد الشعشوع
10,Vaini,TO,75.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
11,Venice,US,77.99,clear sky,27.0998,-82.4543,A Beach Retreat On Casey Key
12,Alofi,NU,75.09,overcast clouds,-19.0595,-169.9187,Taloa Heights
13,Kattivakkam,IN,78.89,overcast clouds,13.2167,80.3167,Euronova Freezer
15,Faanui,PF,78.82,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
17,Carnarvon,AU,66.27,overcast clouds,-24.8667,113.6333,Hospitality Carnarvon
21,Buala,SB,79.56,overcast clouds,-8.1450,159.5921,Maringe Lagoon Lodge
22,Avarua,CK,75.25,light rain,-21.2078,-159.7750,Paradise Inn
23,Port Elizabeth,ZA,64.69,clear sky,-33.9180,25.5701,39 On Nile Guest House
24,Kapaa,US,75.52,heavy intensity rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
33,Saint George,US,75.67,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
34,Ushuaia,AR,55.06,broken clouds,-54.8000,-68.3000,Albatros Hotel
41,Saldanha,ZA,66.25,overcast clouds,-33.0117,17.9442,Blue Bay Lodge
42,Port Lincoln,AU,57.24,broken clouds,-34.7333,135.8667,Port Lincoln Hotel
45,San Julian,MX,74.19,few clouds,21.0167,-102.1667,La Nueva España
46,Hilo,US,79.29,few clouds,19.7297,-155.0900,Hilo Hawaiian Hotel

In [10]:
hotel_df.count()

City           279
Country        279
Max Temp       279
Description    279
Lat            279
Lng            279
Hotel Name     279
dtype: int64

In [11]:
#identiy blank imported hotel names and change to NaN
hotel_df.loc[(hotel_df["Hotel Name"] == ''), :] = np.nan
hotel_df

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
2,Rikitea,PF,73.58,light rain,-23.1203,-134.9692,People ThankYou
5,Bredasdorp,ZA,65.52,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
6,Geraldton,AU,63.01,overcast clouds,-28.7667,114.6000,Broadwater Mariner Resort
9,Faya,SA,64.51,clear sky,18.3851,42.4509,املاك خالد الشعشوع
10,Vaini,TO,75.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
...,...,...,...,...,...,...,...
678,Toamasina,MG,74.35,clear sky,-18.1667,49.3833,Hotel H1
679,Jining,CN,57.96,overcast clouds,35.4050,116.5814,Yunhe Star Hotel
680,Pimentel,PE,73.69,clear sky,-6.8367,-79.9342,Casona Del Muelle
681,Ucluelet,CA,57.04,overcast clouds,48.9329,-125.5528,Black Rock Oceanfront Resort
685,Kharela,IN,72.75,clear sky,25.5500,79.8167,SHANTI MOTORS KHARELA

In [12]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()
# drop hotel with "  " as name according to Google
#hotel_clean_df = hotel_clean_df.drop(hotel_clean_df.index[2])

hotel_clean_df.count()

City           269
Country        269
Max Temp       269
Description    269
Lat            269
Lng            269
Hotel Name     269
dtype: int64

In [13]:
hotel_clean_df.head(20)

,City,Country,Max Temp,Description,Lat,Lng,Hotel Name
2,Rikitea,PF,73.58,light rain,-23.1203,-134.9692,People ThankYou
5,Bredasdorp,ZA,65.52,overcast clouds,-34.5322,20.0403,Bredasdorp Country Manor
6,Geraldton,AU,63.01,overcast clouds,-28.7667,114.6000,Broadwater Mariner Resort
9,Faya,SA,64.51,clear sky,18.3851,42.4509,املاك خالد الشعشوع
10,Vaini,TO,75.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
11,Venice,US,77.99,clear sky,27.0998,-82.4543,A Beach Retreat On Casey Key
12,Alofi,NU,75.09,overcast clouds,-19.0595,-169.9187,Taloa Heights
13,Kattivakkam,IN,78.89,overcast clouds,13.2167,80.3167,Euronova Freezer
15,Faanui,PF,78.82,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
17,Carnarvon,AU,66.27,overcast clouds,-24.8667,113.6333,Hospitality Carnarvon
21,Buala,SB,79.56,overcast clouds,-8.1450,159.5921,Maringe Lagoon Lodge
22,Avarua,CK,75.25,light rain,-21.2078,-159.7750,Paradise Inn
23,Port Elizabeth,ZA,64.69,clear sky,-33.9180,25.5701,39 On Nile Guest House
24,Kapaa,US,75.52,heavy intensity rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
33,Saint George,US,75.67,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
34,Ushuaia,AR,55.06,broken clouds,-54.8000,-68.3000,Albatros Hotel
41,Saldanha,ZA,66.25,overcast clouds,-33.0117,17.9442,Blue Bay Lodge
42,Port Lincoln,AU,57.24,broken clouds,-34.7333,135.8667,Port Lincoln Hotel
45,San Julian,MX,74.19,few clouds,21.0167,-102.1667,La Nueva España
46,Hilo,US,79.29,few clouds,19.7297,-155.0900,Hilo Hawaiian Hotel

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation_search.csv"

# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]
max_temp = hotel_clean_df["Max Temp"]

In [16]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))